# https://docs.docker.com/compose/compose-file/
version: '2.0'

services:
    gateway:
        image: node:8-alpine
        entrypoint: /app/run.sh
        expose:
            - 8000
        ports:
            - '8000:8000'
        volumes:
            - ./:/app

networks:
    default:
        external:
            name: web
